apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot-dex
  description: spring-boot-dex app
  appid: spring-boot-dex
  tags:
    - java
    - springboot
  annotations:
    backstage.io/managed-by-location: https://github.com/NemoAhuja/spring-boot-dex/edit/master/catalog-info.yaml
    github.com/project-slug: 'NemoAhuja/spring-boot-dex'
    cognizant/repo-owner: NemoAhuja
spec:
  type: service
  lifecycle: production
  system: theaterbooking
  owner: user:guest
